# Generated by Django 4.0.4 on 2022-05-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='SubmittionDate',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
    ]
